export const AUTH_START = 'AUTH_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
